language: node_js
deploy:
  provider: s3
  access_key_id: AKIAZHFWQ52F6G55WAUG
  secret_access_key:
    secure: wYXnWJqCLHQ7ppIv5oTsOwr0fnMIc8gzGkH7XU2jXA1D31LYuS++strP9J6fetV57Lg3/WDE7ZlAHa4ZyV9+2OY/GNuo9bhjjjkr1duEYDxyJYwPMheXXycISirmS4+7G0h65CRgRr0A1A10ttcpGqwLU3fa7PocnO1BvGHU0WFZF7phLIty+O9S+wMBkZky2fzs02+Zn45lRjCSy03p5sNEkTxvYrJMBeckgPV8B9DrjQ8zoAS2rpQyRb7UbGG0v20+Sp/3ZaPw+bEziVVgkpT7KgEly0Hcj6LqZb0BSaSovxClOXJUJgW7yAnVBlLebz2ROfLy8wbb4VS7Fb2yEaoWfI4pfZs6sdP6w9Rb+GM63L2EzRaO6WlnaFlh3ucijbWoLvOHLV5r/T/Tqi6ChO66POfFMu19mfbWztDyvQmUbZTELKn7Hf1VJ6O5LXPfO4zdO81NKaKuZoaYdqenTZIRh9TYHOqvbhWaXYpzVIrBvj5gX7jxCFPn2x9kuSSEFYp3XvWRoUHeLlBBKGrG7fpth2ayN8g2c3FpI62pZA+5u3k+fUpgYX3oDvNH0IjZLwscdeFEYpzz3YebVc/RfwGd5axLPWIL4LinjuyYBTddPQvAarxjQd4YBSlP9YqHt282CGnmgKdMwoseQ26enh3RjU2+1s2Q8E/agPtAIK4=
  bucket: bogicevicsasa.com
  acl: public_read_write
  on:
    repo: v0d1ch/bogicevicsasa.com
  region: eu-west-1
